//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryBookSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookOnLoan
    {
        public int OnLoanID { get; set; }
        public int UserID { get; set; }
        public int BookID { get; set; }
        public System.DateTime DateIssued { get; set; }
        public System.DateTime DateDueForReturn { get; set; }
        public Nullable<System.DateTime> ActualDateReturned { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual LibUser LibUser { get; set; }
    }
}
